# Generated by Django 2.1.2 on 2018-11-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='desc',
            new_name='disc',
        ),
    ]
