# Generated by Django 2.1.2 on 2018-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='study_nums',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
