# Generated by Django 2.1.2 on 2018-11-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20181106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
            preserve_default=False,
        ),
    ]
