# Generated by Django 2.1.2 on 2018-11-08 15:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='teacher/%Y/%m', verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='point',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='教学特点'),
            preserve_default=False,
        ),
    ]
