# Generated by Django 2.1.2 on 2018-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181109_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='资源链接'),
        ),
    ]
