# Generated by Django 2.1.2 on 2018-11-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20181108_1533'),
        ('courses', '0007_auto_20181110_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_note',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_note',
            field=models.TextField(default='', verbose_name='教师提示'),
        ),
    ]
