# Generated by Django 2.1.2 on 2018-11-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码'), ('update', '修改邮箱')], max_length=20, verbose_name='发送类型'),
        ),
    ]
